"use client";

import { useState } from "react";
import { cn } from "@/lib/cn";
import { Divider } from "../primitives/Divider";

const QA = [
  {
    q: "Is this a ZK mixer?",
    a: "No. Confidentiality is enforced at the token layer via ERC-7984 and the iExec TDX enclave. No trusted ceremony, no prover infrastructure — just hardware attestation and standard audits.",
  },
  {
    q: "Who can see my position?",
    a: "Only you, by decrypting with your wallet through the Nox gateway. The deployer retains an audit grant per regulatory expectations — that backdoor is opt-out for mainnet deployments.",
  },
  {
    q: "What's the catch with the wrap queue?",
    a: "The wrap step (plaintext → confidential) emits a public amount. Queueing + batch-processing in the enclave breaks the timing link between wrap and destination. Amount privacy remains at the vault layer.",
  },
  {
    q: "How do rates work?",
    a: "Kinked curve, set by the deployer (or a TEE rate-engine in prod). Borrow APR climbs with utilisation; supply APR tracks. Currently read from public state in the vault — individual positions stay encrypted.",
  },
  {
    q: "Is this production-ready?",
    a: "Testnet-live on Arbitrum Sepolia. Audits pending. Mainnet will wait for a formal review of the TEE integration and the FHE proofs generated by Nox's gateway.",
  },
];

export function Faq() {
  const [open, setOpen] = useState<number | null>(0);
  return (
    <section className="px-6 md:px-12 py-24 md:py-32 border-t border-ink-tertiary">
      <div className="max-w-3xl space-y-8">
        <header className="space-y-3">
          <div className="text-[10px] uppercase tracking-[0.3em] text-phos">
            ▸ faq
          </div>
          <h2 className="font-mono text-3xl md:text-4xl text-ink-primary">
            Tell me more.
          </h2>
          <Divider variant="thin" />
        </header>

        <ul className="divide-y divide-ink-tertiary">
          {QA.map((item, i) => {
            const isOpen = open === i;
            return (
              <li key={i} className="py-3">
                <button
                  type="button"
                  onClick={() => setOpen(isOpen ? null : i)}
                  className="cursor-target w-full flex items-baseline gap-2 text-left font-mono group"
                >
                  <span
                    className={cn(
                      "text-phos phos-glow-soft transition-colors",
                      !isOpen && "text-ink-tertiary",
                    )}
                  >
                    &gt;
                  </span>
                  <span className="flex-1 text-ink-primary group-hover:text-phos transition-colors">
                    {item.q}
                  </span>
                  <span className="text-ink-tertiary text-xs">
                    [{isOpen ? "-" : "+"}]
                  </span>
                </button>
                <div
                  className={cn(
                    "overflow-hidden transition-[max-height] duration-300",
                    isOpen ? "max-h-40" : "max-h-0",
                  )}
                >
                  <p className="pt-3 pl-5 text-sm text-ink-secondary leading-relaxed">
                    {item.a}
                  </p>
                </div>
              </li>
            );
          })}
        </ul>
      </div>
    </section>
  );
}
